package ca.gbc.comp3074.snapcal.ui.meals

object DemoMeals {

    data class Ingredient(
        val name: String,
        val quantity: Double,
        val unit: String,
        val category: Category
    )

    enum class Category { meat, seafood, dairy, vegetables, fruits, pantry }
    enum class MealType { breakfast, lunch, dinner, snack }
    enum class GoalType { Lose, Maintain, Gain }

    data class Meal(
        val id: Int,
        val name: String,
        val type: MealType,
        val cuisine: String,
        val goalType: GoalType,
        val calories: Int,
        val icon: String,
        val ingredients: List<Ingredient>,
        val recipeSteps: List<String>
    )

    private fun i(name: String, qty: Double, unit: String, cat: Category) = Ingredient(name, qty, unit, cat)
    private val P = Category.pantry; private val V = Category.vegetables
    private val D = Category.dairy;  private val M = Category.meat
    private val S = Category.seafood; private val F = Category.fruits

    val all: List<Meal> = listOf(

        // ═══════════════════ AMERICAN ═══════════════════
        Meal(1,"Power Breakfast Bowl",MealType.breakfast,"American",GoalType.Maintain,420,"🍳",
            listOf(i("Eggs",3.0,"pcs",D),i("Turkey bacon",4.0,"strips",M),i("Potatoes",2.0,"pcs",V),i("Cheddar cheese",50.0,"g",D),i("Olive oil",1.0,"tbsp",P)),
            listOf("Heat oil in pan","Cook diced potatoes until golden","Scramble eggs","Cook bacon separately","Top with cheese")),
        Meal(2,"Overnight Oats Berry Boost",MealType.breakfast,"American",GoalType.Lose,350,"🥣",
            listOf(i("Rolled oats",80.0,"g",P),i("Greek yogurt",150.0,"g",D),i("Mixed berries",100.0,"g",F),i("Honey",2.0,"tbsp",P),i("Chia seeds",1.0,"tbsp",P)),
            listOf("Mix oats with yogurt","Add honey and chia seeds","Layer with berries","Refrigerate overnight","Enjoy cold")),
        Meal(3,"Classic Pancakes",MealType.breakfast,"American",GoalType.Gain,520,"🥞",
            listOf(i("All-purpose flour",200.0,"g",P),i("Egg",1.0,"pc",D),i("Milk",250.0,"ml",D),i("Butter",30.0,"g",D),i("Maple syrup",3.0,"tbsp",P)),
            listOf("Mix flour, egg, milk into batter","Heat buttered pan","Pour batter, cook until bubbles form","Flip and cook 1 min","Serve with maple syrup")),
        Meal(4,"Grilled Chicken Caesar Salad",MealType.lunch,"American",GoalType.Maintain,450,"🥗",
            listOf(i("Chicken breast",150.0,"g",M),i("Romaine lettuce",200.0,"g",V),i("Parmesan",30.0,"g",D),i("Caesar dressing",2.0,"tbsp",P),i("Croutons",20.0,"g",P)),
            listOf("Season and grill chicken","Chop romaine","Slice chicken","Toss lettuce with dressing","Top with chicken, cheese, croutons")),
        Meal(5,"BBQ Pulled Chicken Wrap",MealType.lunch,"American",GoalType.Gain,580,"🌯",
            listOf(i("Chicken thighs",200.0,"g",M),i("BBQ sauce",3.0,"tbsp",P),i("Flour tortilla",1.0,"pc",P),i("Coleslaw mix",80.0,"g",V),i("Cheddar",40.0,"g",D)),
            listOf("Slow cook chicken with BBQ sauce","Shred chicken","Warm tortilla","Fill with chicken and coleslaw","Roll and serve")),
        Meal(6,"Classic Beef Burger",MealType.dinner,"American",GoalType.Gain,720,"🍔",
            listOf(i("Ground beef",200.0,"g",M),i("Burger bun",1.0,"pc",P),i("Cheddar",30.0,"g",D),i("Lettuce",2.0,"leaves",V),i("Tomato",2.0,"slices",V)),
            listOf("Form beef into patty","Season with salt and pepper","Grill 4 min each side","Add cheese in last minute","Assemble with toppings")),
        Meal(7,"Baked Salmon with Asparagus",MealType.dinner,"American",GoalType.Lose,480,"🐟",
            listOf(i("Salmon fillet",200.0,"g",S),i("Asparagus",200.0,"g",V),i("Olive oil",2.0,"tbsp",P),i("Garlic",2.0,"cloves",V),i("Lemon",1.0,"pc",F)),
            listOf("Preheat oven 400°F","Season salmon with lemon and garlic","Toss asparagus in oil","Bake everything 15 min","Serve together")),
        Meal(8,"Apple Peanut Butter Snack",MealType.snack,"American",GoalType.Maintain,220,"🍎",
            listOf(i("Apple",1.0,"pc",F),i("Peanut butter",2.0,"tbsp",P)),
            listOf("Core and slice apple","Serve with peanut butter for dipping")),
        Meal(9,"Greek Yogurt Parfait",MealType.snack,"American",GoalType.Lose,180,"🥛",
            listOf(i("Greek yogurt",150.0,"g",D),i("Mixed berries",80.0,"g",F),i("Granola",30.0,"g",P)),
            listOf("Layer yogurt in glass","Add berries","Top with granola","Drizzle honey if desired")),
        Meal(10,"Turkey Meatball Pasta",MealType.dinner,"American",GoalType.Maintain,560,"🍝",
            listOf(i("Ground turkey",150.0,"g",M),i("Whole wheat pasta",80.0,"g",P),i("Marinara sauce",150.0,"ml",P),i("Mozzarella",40.0,"g",D),i("Basil",5.0,"g",V)),
            listOf("Form turkey into meatballs","Brown meatballs in pan","Cook pasta al dente","Add marinara to meatballs","Serve over pasta with cheese")),

        // ═══════════════════ MEDITERRANEAN ═══════════════════
        Meal(11,"Avocado Toast Deluxe",MealType.breakfast,"Mediterranean",GoalType.Lose,380,"🥑",
            listOf(i("Whole grain bread",2.0,"slices",P),i("Avocado",1.0,"pc",F),i("Cherry tomatoes",6.0,"pcs",V),i("Feta cheese",30.0,"g",D),i("Lemon juice",1.0,"tbsp",P)),
            listOf("Toast bread until golden","Mash avocado with lemon","Spread on toast","Top with tomatoes and feta","Season with salt and pepper")),
        Meal(12,"Greek Yogurt Berry Bowl",MealType.breakfast,"Mediterranean",GoalType.Lose,300,"🫐",
            listOf(i("Greek yogurt",200.0,"g",D),i("Blueberries",80.0,"g",F),i("Walnuts",20.0,"g",P),i("Honey",1.0,"tbsp",P),i("Cinnamon",0.5,"tsp",P)),
            listOf("Spoon yogurt into bowl","Add fresh blueberries","Sprinkle walnuts","Drizzle honey","Dust with cinnamon")),
        Meal(13,"Falafel Pita Wrap",MealType.lunch,"Mediterranean",GoalType.Maintain,460,"🥙",
            listOf(i("Chickpeas",200.0,"g",P),i("Pita bread",1.0,"pc",P),i("Tzatziki",3.0,"tbsp",D),i("Tomato",1.0,"pc",V),i("Cucumber",0.5,"pc",V)),
            listOf("Blend chickpeas with spices","Form into balls and fry","Warm pita","Add falafel and veggies","Drizzle tzatziki")),
        Meal(14,"Mediterranean Quinoa Bowl",MealType.lunch,"Mediterranean",GoalType.Maintain,460,"🫙",
            listOf(i("Quinoa",80.0,"g",P),i("Grilled chicken",120.0,"g",M),i("Feta",50.0,"g",D),i("Olives",30.0,"g",P),i("Cucumber",100.0,"g",V)),
            listOf("Cook quinoa","Grill and slice chicken","Dice cucumber","Combine all ingredients","Drizzle olive oil and herbs")),
        Meal(15,"Herb Grilled Fish",MealType.dinner,"Mediterranean",GoalType.Lose,420,"🐠",
            listOf(i("White fish fillet",200.0,"g",S),i("Lemon",1.0,"pc",F),i("Fresh herbs",15.0,"g",V),i("Olive oil",2.0,"tbsp",P),i("Garlic",3.0,"cloves",V)),
            listOf("Marinate fish in lemon and herbs","Preheat grill","Grill fish 4 min each side","Roast cherry tomatoes alongside","Plate with lemon wedge")),
        Meal(16,"Lamb Kofta with Rice",MealType.dinner,"Mediterranean",GoalType.Gain,620,"🍢",
            listOf(i("Ground lamb",200.0,"g",M),i("Basmati rice",100.0,"g",P),i("Onion",1.0,"pc",V),i("Cumin",1.0,"tsp",P),i("Plain yogurt",100.0,"g",D)),
            listOf("Mix lamb with spices and onion","Shape onto skewers","Grill kofta 8 min turning","Cook rice","Serve with yogurt sauce")),
        Meal(17,"Hummus Veggie Plate",MealType.snack,"Mediterranean",GoalType.Lose,190,"🥕",
            listOf(i("Hummus",80.0,"g",P),i("Carrots",100.0,"g",V),i("Cucumber",100.0,"g",V),i("Bell pepper",1.0,"pc",V)),
            listOf("Slice all vegetables","Arrange on plate","Serve with hummus for dipping")),
        Meal(18,"Shakshuka",MealType.breakfast,"Mediterranean",GoalType.Maintain,380,"🍳",
            listOf(i("Eggs",3.0,"pcs",D),i("Canned tomatoes",400.0,"g",V),i("Bell pepper",1.0,"pc",V),i("Onion",1.0,"pc",V),i("Paprika",1.0,"tsp",P)),
            listOf("Sauté onion and pepper","Add tomatoes and spices","Simmer 10 min","Create wells, crack eggs in","Cover and cook until eggs set")),

        // ═══════════════════ ITALIAN ═══════════════════
        Meal(19,"Frittata Margherita",MealType.breakfast,"Italian",GoalType.Maintain,390,"🍅",
            listOf(i("Eggs",4.0,"pcs",D),i("Mozzarella",60.0,"g",D),i("Cherry tomatoes",100.0,"g",V),i("Basil",5.0,"g",V),i("Olive oil",1.0,"tbsp",P)),
            listOf("Preheat oven 375°F","Whisk eggs with salt","Sauté tomatoes in oven-safe pan","Pour eggs over, add mozzarella","Bake 10 min until set")),
        Meal(20,"Caprese Salad",MealType.lunch,"Italian",GoalType.Lose,320,"🥗",
            listOf(i("Fresh mozzarella",150.0,"g",D),i("Tomatoes",3.0,"pcs",V),i("Basil",10.0,"g",V),i("Olive oil",2.0,"tbsp",P),i("Balsamic glaze",1.0,"tbsp",P)),
            listOf("Slice mozzarella and tomatoes","Alternate on plate with basil","Drizzle olive oil","Drizzle balsamic glaze","Season with salt and pepper")),
        Meal(21,"Spaghetti Carbonara",MealType.dinner,"Italian",GoalType.Maintain,580,"🍝",
            listOf(i("Spaghetti",100.0,"g",P),i("Pancetta",80.0,"g",M),i("Eggs",2.0,"pcs",D),i("Parmesan",50.0,"g",D),i("Black pepper",1.0,"tsp",P)),
            listOf("Cook spaghetti al dente","Fry pancetta until crispy","Mix eggs and parmesan","Combine hot pasta with pancetta","Add egg mixture off heat, toss fast")),
        Meal(22,"Margherita Pizza",MealType.dinner,"Italian",GoalType.Gain,640,"🍕",
            listOf(i("Pizza dough",200.0,"g",P),i("Tomato sauce",4.0,"tbsp",P),i("Mozzarella",120.0,"g",D),i("Basil",5.0,"g",V),i("Olive oil",1.0,"tbsp",P)),
            listOf("Preheat oven 480°F","Stretch dough onto tray","Spread tomato sauce","Add mozzarella pieces","Bake 10 min, top with fresh basil")),
        Meal(23,"Risotto ai Funghi",MealType.dinner,"Italian",GoalType.Maintain,520,"🍄",
            listOf(i("Arborio rice",100.0,"g",P),i("Mixed mushrooms",200.0,"g",V),i("Parmesan",40.0,"g",D),i("White wine",50.0,"ml",P),i("Vegetable stock",500.0,"ml",P)),
            listOf("Sauté mushrooms and set aside","Toast rice in pan","Add wine and stir","Add stock ladle by ladle stirring","Finish with parmesan and mushrooms")),
        Meal(24,"Bruschetta",MealType.snack,"Italian",GoalType.Lose,200,"🍞",
            listOf(i("Baguette slices",3.0,"pcs",P),i("Tomatoes",2.0,"pcs",V),i("Garlic",2.0,"cloves",V),i("Basil",5.0,"g",V),i("Olive oil",2.0,"tbsp",P)),
            listOf("Toast bread","Rub with garlic clove","Dice tomatoes with basil","Top bread with tomato mix","Drizzle olive oil")),
        Meal(25,"Chicken Piccata",MealType.dinner,"Italian",GoalType.Lose,440,"🍋",
            listOf(i("Chicken breast",180.0,"g",M),i("Capers",2.0,"tbsp",P),i("Lemon juice",3.0,"tbsp",P),i("White wine",50.0,"ml",P),i("Butter",20.0,"g",D)),
            listOf("Pound chicken thin","Dredge in flour and season","Pan-fry until golden","Remove chicken, deglaze with wine and lemon","Add capers and butter, pour over chicken")),

        // ═══════════════════ CHINESE ═══════════════════
        Meal(26,"Congee Rice Porridge",MealType.breakfast,"Chinese",GoalType.Lose,280,"🍚",
            listOf(i("Jasmine rice",60.0,"g",P),i("Chicken stock",600.0,"ml",P),i("Ginger",5.0,"g",V),i("Spring onion",2.0,"stalks",V),i("Soy sauce",1.0,"tsp",P)),
            listOf("Bring stock to boil","Add rice and ginger","Simmer 30 min stirring occasionally","Season with soy sauce","Garnish with spring onion")),
        Meal(27,"Dim Sum Steamed Dumplings",MealType.snack,"Chinese",GoalType.Maintain,280,"🥟",
            listOf(i("Pork mince",150.0,"g",M),i("Dumpling wrappers",12.0,"pcs",P),i("Cabbage",80.0,"g",V),i("Sesame oil",1.0,"tsp",P),i("Soy sauce",2.0,"tbsp",P)),
            listOf("Mix pork, cabbage, sesame oil","Place filling on wrapper","Fold and pleat edges","Steam 8 min","Serve with dipping sauce")),
        Meal(28,"Kung Pao Chicken",MealType.lunch,"Chinese",GoalType.Maintain,480,"🌶️",
            listOf(i("Chicken breast",180.0,"g",M),i("Peanuts",40.0,"g",P),i("Bell peppers",2.0,"pcs",V),i("Dried chilies",6.0,"pcs",P),i("Soy sauce",3.0,"tbsp",P)),
            listOf("Marinate chicken in soy sauce","Stir-fry chicken until cooked","Add peppers and chilies","Add peanuts and sauce","Serve over rice")),
        Meal(29,"Sweet and Sour Pork",MealType.dinner,"Chinese",GoalType.Gain,600,"🍖",
            listOf(i("Pork loin",200.0,"g",M),i("Pineapple chunks",100.0,"g",F),i("Bell peppers",2.0,"pcs",V),i("Vinegar",2.0,"tbsp",P),i("Sugar",2.0,"tbsp",P)),
            listOf("Cut and marinate pork","Batter and fry pork","Make sweet sour sauce","Stir-fry peppers and pineapple","Combine all and serve with rice")),
        Meal(30,"Fried Rice",MealType.lunch,"Chinese",GoalType.Maintain,440,"🍳",
            listOf(i("Cooked rice",200.0,"g",P),i("Eggs",2.0,"pcs",D),i("Mixed vegetables",150.0,"g",V),i("Soy sauce",3.0,"tbsp",P),i("Sesame oil",1.0,"tsp",P)),
            listOf("Heat wok until smoking","Scramble eggs and set aside","Stir-fry vegetables","Add rice and toss","Add eggs, soy sauce, sesame oil")),
        Meal(31,"Steamed Fish with Ginger",MealType.dinner,"Chinese",GoalType.Lose,360,"🐟",
            listOf(i("White fish",200.0,"g",S),i("Ginger",15.0,"g",V),i("Spring onion",3.0,"stalks",V),i("Soy sauce",3.0,"tbsp",P),i("Sesame oil",1.0,"tsp",P)),
            listOf("Score fish and fill with ginger","Steam 12 min","Heat oil in pan until smoking","Pour soy sauce over fish","Pour hot oil over fish — it will sizzle")),
        Meal(32,"Mapo Tofu",MealType.dinner,"Chinese",GoalType.Lose,380,"🌶️",
            listOf(i("Soft tofu",300.0,"g",D),i("Pork mince",100.0,"g",M),i("Doubanjiang",2.0,"tbsp",P),i("Garlic",3.0,"cloves",V),i("Sichuan peppercorn",1.0,"tsp",P)),
            listOf("Fry pork mince until brown","Add doubanjiang and garlic","Add stock and bring to simmer","Add tofu cubes gently","Finish with Sichuan peppercorn oil")),

        // ═══════════════════ JAPANESE ═══════════════════
        Meal(33,"Tamagoyaki Bento",MealType.breakfast,"Japanese",GoalType.Maintain,340,"🥚",
            listOf(i("Eggs",3.0,"pcs",D),i("Mirin",2.0,"tsp",P),i("Soy sauce",1.0,"tsp",P),i("Dashi stock",2.0,"tbsp",P),i("Steamed rice",150.0,"g",P)),
            listOf("Mix eggs with mirin, soy, dashi","Heat rectangular pan with oil","Pour egg layer, roll as it cooks","Repeat layers to build roll","Slice and serve with rice")),
        Meal(34,"Miso Soup",MealType.snack,"Japanese",GoalType.Lose,80,"🍜",
            listOf(i("Miso paste",2.0,"tbsp",P),i("Tofu",100.0,"g",D),i("Wakame seaweed",5.0,"g",P),i("Spring onion",1.0,"stalk",V),i("Dashi stock",400.0,"ml",P)),
            listOf("Heat dashi stock","Dissolve miso in ladle of stock","Add tofu and seaweed","Do not boil after adding miso","Garnish with spring onion")),
        Meal(35,"Chicken Teriyaki Bowl",MealType.lunch,"Japanese",GoalType.Maintain,520,"🍱",
            listOf(i("Chicken thighs",180.0,"g",M),i("Soy sauce",3.0,"tbsp",P),i("Mirin",2.0,"tbsp",P),i("Brown sugar",1.0,"tbsp",P),i("Steamed rice",150.0,"g",P)),
            listOf("Mix soy, mirin, sugar for sauce","Grill chicken skin-side down","Brush sauce repeatedly while cooking","Slice chicken","Serve over rice with sauce")),
        Meal(36,"Salmon Sushi Bowl",MealType.lunch,"Japanese",GoalType.Lose,490,"🍣",
            listOf(i("Sushi rice",150.0,"g",P),i("Fresh salmon",120.0,"g",S),i("Cucumber",0.5,"pc",V),i("Avocado",0.5,"pc",F),i("Soy sauce",2.0,"tbsp",P)),
            listOf("Season rice with vinegar","Slice salmon and vegetables","Arrange over rice","Add sliced avocado","Serve with soy sauce and wasabi")),
        Meal(37,"Katsu Curry",MealType.dinner,"Japanese",GoalType.Gain,680,"🍛",
            listOf(i("Chicken breast",180.0,"g",M),i("Curry roux",100.0,"g",P),i("Potato",1.0,"pc",V),i("Carrot",1.0,"pc",V),i("Steamed rice",150.0,"g",P)),
            listOf("Bread and fry chicken cutlet","Simmer curry with veg until soft","Add roux and stir until thick","Serve rice on one side","Slice katsu on top with curry alongside")),
        Meal(38,"Ramen",MealType.dinner,"Japanese",GoalType.Maintain,560,"🍜",
            listOf(i("Ramen noodles",100.0,"g",P),i("Pork belly",100.0,"g",M),i("Soft boiled egg",1.0,"pc",D),i("Nori seaweed",2.0,"sheets",P),i("Miso broth",500.0,"ml",P)),
            listOf("Prepare miso broth","Simmer pork belly 2 hours","Soft boil eggs 7 min","Cook noodles separately","Assemble bowl with all toppings")),

        // ═══════════════════ MEXICAN ═══════════════════
        Meal(39,"Huevos Rancheros",MealType.breakfast,"Mexican",GoalType.Maintain,420,"🍳",
            listOf(i("Eggs",2.0,"pcs",D),i("Corn tortillas",2.0,"pcs",P),i("Salsa roja",4.0,"tbsp",P),i("Refried beans",100.0,"g",P),i("Cheddar",30.0,"g",D)),
            listOf("Warm tortillas","Spread refried beans","Top with fried eggs","Pour warm salsa over","Sprinkle cheese")),
        Meal(40,"Chicken Quesadilla",MealType.snack,"Mexican",GoalType.Maintain,380,"🫓",
            listOf(i("Chicken breast",100.0,"g",M),i("Flour tortilla",2.0,"pcs",P),i("Cheddar",60.0,"g",D),i("Bell pepper",0.5,"pc",V),i("Salsa",2.0,"tbsp",P)),
            listOf("Cook and shred chicken","Place tortilla in pan","Add chicken, cheese, pepper","Top with second tortilla","Cook until golden, flip, serve")),
        Meal(41,"Fish Tacos",MealType.lunch,"Mexican",GoalType.Lose,420,"🌮",
            listOf(i("White fish",180.0,"g",S),i("Corn tortillas",3.0,"pcs",P),i("Cabbage slaw",80.0,"g",V),i("Lime",1.0,"pc",F),i("Chipotle mayo",2.0,"tbsp",D)),
            listOf("Season and grill fish","Warm tortillas","Break fish into chunks","Build tacos with slaw","Drizzle chipotle mayo and lime")),
        Meal(42,"Beef Burrito",MealType.lunch,"Mexican",GoalType.Gain,640,"🌯",
            listOf(i("Ground beef",180.0,"g",M),i("Large flour tortilla",1.0,"pc",P),i("Mexican rice",100.0,"g",P),i("Black beans",80.0,"g",P),i("Guacamole",3.0,"tbsp",F)),
            listOf("Season and cook beef","Warm tortilla","Layer rice, beans, beef","Add guacamole and salsa","Roll tightly and serve")),
        Meal(43,"Chicken Enchiladas",MealType.dinner,"Mexican",GoalType.Maintain,540,"🫔",
            listOf(i("Chicken breast",200.0,"g",M),i("Corn tortillas",4.0,"pcs",P),i("Enchilada sauce",200.0,"ml",P),i("Mozzarella",80.0,"g",D),i("Sour cream",3.0,"tbsp",D)),
            listOf("Cook and shred chicken","Dip tortillas in sauce","Fill with chicken and roll","Place in baking dish","Pour sauce, add cheese, bake 20 min")),
        Meal(44,"Carne Asada Bowl",MealType.dinner,"Mexican",GoalType.Gain,680,"🥩",
            listOf(i("Flank steak",200.0,"g",M),i("Cilantro lime rice",150.0,"g",P),i("Black beans",100.0,"g",P),i("Pico de gallo",80.0,"g",V),i("Avocado",1.0,"pc",F)),
            listOf("Marinate steak in citrus and spices","Grill steak 4 min each side","Rest and slice thin against grain","Cook rice with cilantro and lime","Bowl up with beans, pico, avocado")),
        Meal(45,"Guacamole with Chips",MealType.snack,"Mexican",GoalType.Maintain,240,"🥑",
            listOf(i("Avocado",2.0,"pcs",F),i("Lime juice",2.0,"tbsp",F),i("Red onion",0.25,"pc",V),i("Cilantro",5.0,"g",V),i("Tortilla chips",30.0,"g",P)),
            listOf("Mash avocados","Add lime juice and salt","Mix in onion and cilantro","Adjust seasoning","Serve with chips")),

        // ═══════════════════ INDIAN ═══════════════════
        Meal(46,"Masala Omelette",MealType.breakfast,"Indian",GoalType.Lose,310,"🍳",
            listOf(i("Eggs",3.0,"pcs",D),i("Onion",0.5,"pc",V),i("Green chili",1.0,"pc",V),i("Tomato",0.5,"pc",V),i("Cumin seeds",0.5,"tsp",P)),
            listOf("Whisk eggs with salt","Sauté onion, chili, tomato","Add cumin seeds","Pour eggs and cook","Fold and serve with toast")),
        Meal(47,"Poha",MealType.breakfast,"Indian",GoalType.Lose,320,"🍚",
            listOf(i("Flattened rice",80.0,"g",P),i("Onion",1.0,"pc",V),i("Peas",50.0,"g",V),i("Mustard seeds",0.5,"tsp",P),i("Turmeric",0.25,"tsp",P)),
            listOf("Rinse poha until soft","Temper mustard seeds in oil","Sauté onion and peas","Add poha and turmeric","Cook 3 min, serve with lime")),
        Meal(48,"Dal Tadka",MealType.lunch,"Indian",GoalType.Lose,360,"🥘",
            listOf(i("Yellow lentils",100.0,"g",P),i("Onion",1.0,"pc",V),i("Tomatoes",2.0,"pcs",V),i("Garlic",4.0,"cloves",V),i("Ghee",1.0,"tbsp",D)),
            listOf("Pressure cook lentils until soft","Fry onion, garlic, tomatoes","Add spices: cumin, turmeric, chili","Add lentils and simmer","Finish with ghee tadka on top")),
        Meal(49,"Paneer Tikka",MealType.snack,"Indian",GoalType.Maintain,320,"🧀",
            listOf(i("Paneer",200.0,"g",D),i("Yogurt",80.0,"g",D),i("Bell peppers",2.0,"pcs",V),i("Tikka spice mix",2.0,"tbsp",P),i("Lemon juice",1.0,"tbsp",F)),
            listOf("Cube paneer and peppers","Marinate in yogurt and spices 1 hour","Thread onto skewers","Grill or broil 10 min","Serve with mint chutney")),
        Meal(50,"Butter Chicken",MealType.dinner,"Indian",GoalType.Gain,620,"🍛",
            listOf(i("Chicken thighs",200.0,"g",M),i("Butter",30.0,"g",D),i("Cream",80.0,"ml",D),i("Tomato purée",150.0,"ml",P),i("Garam masala",2.0,"tsp",P)),
            listOf("Marinate chicken in yogurt and spices","Grill or bake chicken","Make sauce with butter, tomato, cream","Add grilled chicken to sauce","Simmer 10 min, serve with naan")),
        Meal(51,"Palak Paneer",MealType.dinner,"Indian",GoalType.Maintain,480,"🌿",
            listOf(i("Spinach",300.0,"g",V),i("Paneer",150.0,"g",D),i("Onion",1.0,"pc",V),i("Garlic",3.0,"cloves",V),i("Cream",50.0,"ml",D)),
            listOf("Blanch spinach, blend smooth","Sauté onion and garlic","Add spinach purée and spices","Add cubed paneer","Stir in cream and simmer 5 min")),
        Meal(52,"Biryani",MealType.dinner,"Indian",GoalType.Gain,700,"🍚",
            listOf(i("Basmati rice",150.0,"g",P),i("Chicken",200.0,"g",M),i("Onion",2.0,"pcs",V),i("Yogurt",100.0,"g",D),i("Saffron",0.5,"tsp",P)),
            listOf("Marinate chicken in yogurt and biryani spices","Par-cook rice until 70% done","Layer chicken and rice in pot","Cook on dum (sealed) 30 min","Serve with raita")),
        Meal(53,"Chana Masala",MealType.lunch,"Indian",GoalType.Lose,380,"🫛",
            listOf(i("Chickpeas",200.0,"g",P),i("Tomatoes",2.0,"pcs",V),i("Onion",1.0,"pc",V),i("Chole masala",2.0,"tbsp",P),i("Ginger",10.0,"g",V)),
            listOf("Sauté onion and ginger","Add tomatoes and cook down","Add chole masala spices","Add chickpeas and water","Simmer 20 min until thick")),

        // ═══════════════════ PAKISTANI ═══════════════════
        Meal(54,"Paratha with Omelette",MealType.breakfast,"Pakistani",GoalType.Gain,610,"🫓",
            listOf(i("Whole wheat flour",150.0,"g",P),i("Ghee",2.0,"tbsp",D),i("Eggs",2.0,"pcs",D),i("Onion",0.5,"pc",V),i("Chai milk",100.0,"ml",D)),
            listOf("Knead dough with ghee and water","Roll and fold parathas","Cook on tawa with ghee","Make omelette with onion","Serve together with chai")),
        Meal(55,"Nihari",MealType.lunch,"Pakistani",GoalType.Gain,680,"🍖",
            listOf(i("Beef shank",250.0,"g",M),i("Nihari masala",3.0,"tbsp",P),i("Ginger",15.0,"g",V),i("Naan",2.0,"pcs",P),i("Fried onions",30.0,"g",V)),
            listOf("Marinate beef with nihari masala","Slow cook 3 hours until tender","Make flour paste to thicken gravy","Adjust seasoning","Garnish with ginger and serve with naan")),
        Meal(56,"Karahi Chicken",MealType.dinner,"Pakistani",GoalType.Maintain,520,"🍗",
            listOf(i("Chicken",350.0,"g",M),i("Tomatoes",4.0,"pcs",V),i("Ginger",20.0,"g",V),i("Green chilies",4.0,"pcs",V),i("Oil",3.0,"tbsp",P)),
            listOf("Heat oil in karahi (wok)","Add chicken and sear","Add tomatoes and cook down","Add ginger, chilies, spices","Cook until oil separates")),
        Meal(57,"Daal Chawal",MealType.lunch,"Pakistani",GoalType.Lose,420,"🍚",
            listOf(i("Masoor lentils",100.0,"g",P),i("Basmati rice",120.0,"g",P),i("Onion",1.0,"pc",V),i("Tomato",2.0,"pcs",V),i("Tarka spices",2.0,"tsp",P)),
            listOf("Cook lentils until soft","Prepare tarka with onion and tomato","Pour tarka over lentils","Cook basmati rice separately","Serve daal over rice")),
        Meal(58,"Seekh Kebab",MealType.dinner,"Pakistani",GoalType.Maintain,460,"🍢",
            listOf(i("Ground beef",200.0,"g",M),i("Onion",0.5,"pc",V),i("Green chili",2.0,"pcs",V),i("Coriander",10.0,"g",V),i("Kebab masala",2.0,"tsp",P)),
            listOf("Mix beef with spices and herbs","Shape onto flat skewers","Grill on coal or pan 8 min","Turn halfway through","Serve with naan and raita")),
        Meal(59,"Haleem",MealType.dinner,"Pakistani",GoalType.Gain,640,"🥘",
            listOf(i("Beef",200.0,"g",M),i("Wheat berries",60.0,"g",P),i("Mixed lentils",80.0,"g",P),i("Haleem masala",3.0,"tbsp",P),i("Fried onions",30.0,"g",V)),
            listOf("Slow cook beef until very tender","Cook wheat and lentils soft","Blend everything together roughly","Season with haleem masala","Garnish with fried onions and ginger")),
        Meal(60,"Samosas",MealType.snack,"Pakistani",GoalType.Maintain,260,"🔺",
            listOf(i("Samosa wrappers",6.0,"pcs",P),i("Potato",2.0,"pcs",V),i("Green peas",50.0,"g",V),i("Cumin seeds",1.0,"tsp",P),i("Oil for frying",3.0,"tbsp",P)),
            listOf("Boil and mash potatoes with peas","Add cumin and spices","Fill samosa wrappers","Seal edges with water","Deep fry until golden")),

        // ═══════════════════ THAI ═══════════════════
        Meal(61,"Pad Thai",MealType.lunch,"Thai",GoalType.Maintain,500,"🍜",
            listOf(i("Rice noodles",100.0,"g",P),i("Shrimp",150.0,"g",S),i("Eggs",2.0,"pcs",D),i("Bean sprouts",80.0,"g",V),i("Pad Thai sauce",3.0,"tbsp",P)),
            listOf("Soak noodles until soft","Stir-fry shrimp until pink","Push to side, scramble eggs","Add noodles and sauce","Toss all together, top with sprouts and peanuts")),
        Meal(62,"Green Curry",MealType.dinner,"Thai",GoalType.Maintain,520,"🥥",
            listOf(i("Chicken breast",180.0,"g",M),i("Coconut milk",300.0,"ml",P),i("Green curry paste",3.0,"tbsp",P),i("Thai eggplant",150.0,"g",V),i("Thai basil",10.0,"g",V)),
            listOf("Fry curry paste in oil","Add coconut milk and bring to simmer","Add chicken and eggplant","Cook 15 min until chicken done","Add basil and serve with jasmine rice")),
        Meal(63,"Tom Yum Soup",MealType.lunch,"Thai",GoalType.Lose,280,"🍲",
            listOf(i("Shrimp",150.0,"g",S),i("Mushrooms",100.0,"g",V),i("Lemongrass",2.0,"stalks",V),i("Lime leaves",4.0,"pcs",V),i("Fish sauce",2.0,"tbsp",P)),
            listOf("Boil lemongrass and lime leaves","Add mushrooms and cook","Add shrimp and fish sauce","Add tom yum paste","Finish with lime juice and chili")),
        Meal(64,"Mango Sticky Rice",MealType.snack,"Thai",GoalType.Gain,380,"🥭",
            listOf(i("Glutinous rice",100.0,"g",P),i("Mango",1.0,"pc",F),i("Coconut milk",150.0,"ml",P),i("Sugar",2.0,"tbsp",P),i("Sesame seeds",1.0,"tsp",P)),
            listOf("Steam glutinous rice 20 min","Heat coconut milk with sugar","Mix rice with coconut milk","Slice fresh mango","Serve rice with mango, drizzle remaining coconut milk")),
        Meal(65,"Pad See Ew",MealType.dinner,"Thai",GoalType.Gain,580,"🥦",
            listOf(i("Wide rice noodles",120.0,"g",P),i("Beef",150.0,"g",M),i("Chinese broccoli",100.0,"g",V),i("Eggs",2.0,"pcs",D),i("Dark soy sauce",3.0,"tbsp",P)),
            listOf("Sear beef in hot wok","Scramble eggs alongside","Add noodles and soy sauce","Toss in broccoli","Stir-fry on high heat until slightly charred")),

        // ═══════════════════ KOREAN ═══════════════════
        Meal(66,"Korean Egg Rice",MealType.breakfast,"Korean",GoalType.Maintain,380,"🍚",
            listOf(i("Steamed rice",200.0,"g",P),i("Egg",1.0,"pc",D),i("Gochujang",1.0,"tbsp",P),i("Sesame oil",1.0,"tsp",P),i("Kimchi",50.0,"g",V)),
            listOf("Cook rice","Top with fried egg","Add spoonful of gochujang","Drizzle sesame oil","Serve with kimchi on side")),
        Meal(67,"Bibimbap",MealType.lunch,"Korean",GoalType.Maintain,520,"🥗",
            listOf(i("Steamed rice",150.0,"g",P),i("Beef mince",100.0,"g",M),i("Mixed vegetables",200.0,"g",V),i("Egg",1.0,"pc",D),i("Gochujang sauce",2.0,"tbsp",P)),
            listOf("Cook rice and keep warm","Sauté beef with garlic and soy","Cook each vegetable separately","Place all in bowl over rice","Top with fried egg and gochujang")),
        Meal(68,"Bulgogi",MealType.dinner,"Korean",GoalType.Maintain,520,"🥩",
            listOf(i("Beef sirloin",200.0,"g",M),i("Soy sauce",4.0,"tbsp",P),i("Pear",0.5,"pc",F),i("Sesame oil",2.0,"tsp",P),i("Spring onion",3.0,"stalks",V)),
            listOf("Grate pear into marinade","Mix with soy sauce, sesame oil","Marinate sliced beef 2 hours","Grill on hot grill pan","Serve with rice and banchan")),
        Meal(69,"Tteokbokki",MealType.snack,"Korean",GoalType.Maintain,320,"🌶️",
            listOf(i("Rice cakes",200.0,"g",P),i("Gochujang",3.0,"tbsp",P),i("Fish cakes",100.0,"g",S),i("Spring onion",2.0,"stalks",V),i("Sugar",1.0,"tbsp",P)),
            listOf("Boil rice cakes until soft","Mix gochujang sauce with sugar and stock","Add rice cakes and fish cakes","Simmer until sauce thickens","Garnish with spring onion")),
        Meal(70,"Korean Fried Chicken",MealType.dinner,"Korean",GoalType.Gain,660,"🍗",
            listOf(i("Chicken wings",400.0,"g",M),i("Gochujang sauce",4.0,"tbsp",P),i("Soy sauce",2.0,"tbsp",P),i("Garlic",4.0,"cloves",V),i("Honey",2.0,"tbsp",P)),
            listOf("Double-fry chicken wings until crispy","Mix sauce ingredients","Toss hot wings in sauce","Garnish with sesame seeds","Serve with pickled radish")),

        // ═══════════════════ LEBANESE ═══════════════════
        Meal(71,"Manakish Zaatar",MealType.breakfast,"Lebanese",GoalType.Maintain,360,"🫓",
            listOf(i("Pita dough",150.0,"g",P),i("Zaatar spice mix",3.0,"tbsp",P),i("Olive oil",3.0,"tbsp",P),i("Tomato",1.0,"pc",V),i("Cucumber",0.5,"pc",V)),
            listOf("Spread zaatar mixed with oil on dough","Bake at 450°F 8 min","Serve hot from oven","Slice tomato and cucumber","Eat with fresh vegetables on side")),
        Meal(72,"Tabbouleh",MealType.lunch,"Lebanese",GoalType.Lose,240,"🌿",
            listOf(i("Bulgur wheat",60.0,"g",P),i("Parsley",100.0,"g",V),i("Tomatoes",2.0,"pcs",V),i("Lemon juice",3.0,"tbsp",F),i("Olive oil",2.0,"tbsp",P)),
            listOf("Soak bulgur in boiling water 20 min","Finely chop parsley","Dice tomatoes small","Mix all with lemon and olive oil","Season and refrigerate 30 min")),
        Meal(73,"Grilled Kafta",MealType.dinner,"Lebanese",GoalType.Maintain,500,"🍢",
            listOf(i("Ground beef",200.0,"g",M),i("Parsley",20.0,"g",V),i("Onion",0.5,"pc",V),i("Lebanese 7-spice",2.0,"tsp",P),i("Pita bread",2.0,"pcs",P)),
            listOf("Mix beef, parsley, onion, spices","Shape onto flat skewers","Grill 8 min turning","Warm pita on grill","Serve kafta in pita with garlic sauce")),
        Meal(74,"Lemon Garlic Shrimp",MealType.dinner,"Lebanese",GoalType.Lose,360,"🍤",
            listOf(i("Large shrimp",200.0,"g",S),i("Garlic",5.0,"cloves",V),i("Lemon",1.0,"pc",F),i("Olive oil",2.0,"tbsp",P),i("Parsley",10.0,"g",V)),
            listOf("Peel and devein shrimp","Sauté garlic in olive oil","Add shrimp and cook 2 min each side","Add lemon juice and parsley","Serve with pita or over rice")),

        // ═══════════════════ TURKISH ═══════════════════
        Meal(75,"Menemen",MealType.breakfast,"Turkish",GoalType.Maintain,350,"🍳",
            listOf(i("Eggs",3.0,"pcs",D),i("Tomatoes",2.0,"pcs",V),i("Green pepper",2.0,"pcs",V),i("Olive oil",2.0,"tbsp",P),i("Feta",40.0,"g",D)),
            listOf("Sauté peppers in olive oil","Add chopped tomatoes","Simmer until soft","Break eggs into pan","Stir gently and cook soft, top with feta")),
        Meal(76,"Turkish Doner Bowl",MealType.lunch,"Turkish",GoalType.Maintain,540,"🥙",
            listOf(i("Lamb or chicken",200.0,"g",M),i("Basmati rice",120.0,"g",P),i("Tzatziki",3.0,"tbsp",D),i("Red cabbage",80.0,"g",V),i("Tomato",1.0,"pc",V)),
            listOf("Marinate and grill meat with doner spices","Cook rice","Slice meat thin","Bowl up rice, meat, vegetables","Add tzatziki on top")),
        Meal(77,"Lahmacun",MealType.lunch,"Turkish",GoalType.Lose,380,"🫓",
            listOf(i("Thin flatbread",2.0,"pcs",P),i("Ground lamb",100.0,"g",M),i("Tomato",2.0,"pcs",V),i("Onion",1.0,"pc",V),i("Parsley",10.0,"g",V)),
            listOf("Blend lamb with tomato, onion, spices","Spread thin on flatbread","Bake 8 min at 480°F","Squeeze lemon over","Roll with fresh parsley and eat")),

        // ═══════════════════ EXTRA SNACKS & LIGHT MEALS ═══════════════════
        Meal(78,"Protein Energy Balls",MealType.snack,"American",GoalType.Gain,240,"⚽",
            listOf(i("Dates",80.0,"g",F),i("Almonds",30.0,"g",P),i("Protein powder",15.0,"g",P),i("Coconut flakes",15.0,"g",P)),
            listOf("Blend dates and almonds","Add protein powder","Form into balls","Roll in coconut flakes","Chill 30 min before eating")),
        Meal(79,"Avocado Crackers",MealType.snack,"Mediterranean",GoalType.Lose,160,"🥑",
            listOf(i("Whole grain crackers",6.0,"pcs",P),i("Avocado",0.5,"pc",F),i("Cherry tomatoes",3.0,"pcs",V),i("Sea salt",0.5,"tsp",P)),
            listOf("Mash avocado with salt","Spread on crackers","Top with tomato slices","Add pepper to taste","Serve immediately")),
        Meal(80,"Cheese and Fruit Plate",MealType.snack,"American",GoalType.Maintain,280,"🍇",
            listOf(i("Cheddar cheese",60.0,"g",D),i("Grapes",80.0,"g",F),i("Apple slices",1.0,"pc",F),i("Whole grain crackers",4.0,"pcs",P)),
            listOf("Slice cheese into pieces","Wash and separate grapes","Slice apple","Arrange on board with crackers","Serve at room temperature")),

        // ═══════════════════ NEWLY ADDED MEALS (81-100) ═══════════════════
        Meal(81,"Veggie Egg White Omelet",MealType.breakfast,"American",GoalType.Lose,280,"🥚",
            listOf(i("Egg whites",4.0,"pcs",D),i("Spinach",50.0,"g",V),i("Mushrooms",50.0,"g",V),i("Bell pepper",0.5,"pc",V)),
            listOf("Whisk egg whites","Sauté vegetables in non-stick pan","Pour egg whites over","Cook until set and fold")),
        Meal(82,"Turkey Club Sandwich",MealType.lunch,"American",GoalType.Maintain,480,"🥪",
            listOf(i("Whole wheat bread",3.0,"slices",P),i("Deli turkey",100.0,"g",M),i("Bacon",1.0,"strip",M),i("Lettuce",1.0,"leaf",V),i("Tomato",2.0,"slices",V)),
            listOf("Toast bread","Layer turkey, bacon, lettuce, tomato","Stack and cut into triangles")),
        Meal(83,"Steak and Loaded Potato",MealType.dinner,"American",GoalType.Gain,750,"🥩",
            listOf(i("Sirloin steak",250.0,"g",M),i("Large potato",1.0,"pc",V),i("Sour cream",2.0,"tbsp",D),i("Cheese",30.0,"g",D),i("Chives",5.0,"g",V)),
            listOf("Grill steak to preference","Bake potato until soft","Slice potato and fill with toppings","Serve together")),
        Meal(84,"Greek Chickpea Salad",MealType.lunch,"Mediterranean",GoalType.Lose,320,"🥗",
            listOf(i("Chickpeas",150.0,"g",P),i("Cucumber",100.0,"g",V),i("Tomato",1.0,"pc",V),i("Feta",30.0,"g",D),i("Olives",20.0,"g",P)),
            listOf("Rinse chickpeas","Dice vegetables","Toss everything with lemon and olive oil")),
        Meal(85,"Roasted Veggie Couscous",MealType.dinner,"Mediterranean",GoalType.Maintain,410,"🌾",
            listOf(i("Couscous",80.0,"g",P),i("Zucchini",100.0,"g",V),i("Eggplant",100.0,"g",V),i("Red onion",0.5,"pc",V)),
            listOf("Prepare couscous","Roast vegetables with herbs","Mix together and serve warm")),
        Meal(86,"Pesto Pasta with Chicken",MealType.lunch,"Italian",GoalType.Maintain,540,"🍝",
            listOf(i("Penne pasta",100.0,"g",P),i("Pesto sauce",3.0,"tbsp",P),i("Chicken breast",120.0,"g",M),i("Parmesan",20.0,"g",D)),
            listOf("Cook pasta","Grill and slice chicken","Toss pasta with pesto and chicken","Top with parmesan")),
        Meal(87,"Lasagna Bolognese",MealType.dinner,"Italian",GoalType.Gain,720,"🥘",
            listOf(i("Lasagna sheets",4.0,"pcs",P),i("Ground beef",150.0,"g",M),i("Ricotta",100.0,"g",D),i("Marinara",150.0,"ml",P),i("Mozzarella",50.0,"g",D)),
            listOf("Layer pasta, meat sauce, and cheeses","Bake at 375°F for 30 min","Let rest before serving")),
        Meal(88,"Scallion Pancakes",MealType.breakfast,"Chinese",GoalType.Maintain,350,"🥞",
            listOf(i("Flour",150.0,"g",P),i("Scallions",20.0,"g",V),i("Sesame oil",1.0,"tsp",P)),
            listOf("Make dough and roll with scallions","Pan-fry until crispy","Slice and serve with soy dip")),
        Meal(89,"Steamed Tofu & Broccoli",MealType.lunch,"Chinese",GoalType.Lose,260,"🥦",
            listOf(i("Firm tofu",200.0,"g",D),i("Broccoli",200.0,"g",V),i("Ginger",5.0,"g",V),i("Soy sauce",2.0,"tbsp",P)),
            listOf("Steam tofu and broccoli","Drizzle with soy sauce and ginger","Serve hot")),
        Meal(90,"Sashimi Deluxe Set",MealType.dinner,"Japanese",GoalType.Lose,380,"🍱",
            listOf(i("Tuna",100.0,"g",S),i("Salmon",100.0,"g",S),i("Yellowtail",100.0,"g",S),i("Radish",50.0,"g",V)),
            listOf("Slice fresh fish thinly","Arrange with shredded radish","Serve with wasabi and soy")),
        Meal(91,"Edamame with Sea Salt",MealType.snack,"Japanese",GoalType.Maintain,150,"🫛",
            listOf(i("Edamame pods",150.0,"g",V),i("Sea salt",1.0,"tsp",P)),
            listOf("Boil or steam pods","Sprinkle with sea salt","Serve warm")),
        Meal(92,"Chorizo Breakfast Burrito",MealType.breakfast,"Mexican",GoalType.Gain,620,"🌯",
            listOf(i("Large tortilla",1.0,"pc",P),i("Chorizo",100.0,"g",M),i("Eggs",2.0,"pcs",D),i("Cheese",40.0,"g",D),i("Hash browns",50.0,"g",V)),
            listOf("Cook chorizo and hash browns","Scramble eggs","Fill tortilla with all and roll")),
        Meal(93,"Lentil Soup (Sopa de Lentejas)",MealType.lunch,"Mexican",GoalType.Lose,310,"🥣",
            listOf(i("Brown lentils",100.0,"g",P),i("Tomato",1.0,"pc",V),i("Cilantro",10.0,"g",V),i("Onion",0.5,"pc",V)),
            listOf("Simmer lentils with veggies","Season with cumin and chili","Garnish with cilantro")),
        Meal(94,"Aloo Gobi (Potato & Cauliflower)",MealType.dinner,"Indian",GoalType.Maintain,380,"🍛",
            listOf(i("Potatoes",150.0,"g",V),i("Cauliflower",200.0,"g",V),i("Turmeric",1.0,"tsp",P),i("Garam Masala",1.0,"tsp",P)),
            listOf("Sauté potatoes and cauliflower with spices","Cook until tender","Serve with roti or rice")),
        Meal(95,"Mango Lassi",MealType.snack,"Indian",GoalType.Gain,320,"🥤",
            listOf(i("Mango pulp",150.0,"g",F),i("Yogurt",200.0,"g",D),i("Sugar",2.0,"tbsp",P),i("Cardamom",0.5,"tsp",P)),
            listOf("Blend all ingredients smooth","Chill and serve")),
        Meal(96,"Chicken Jalfrezi",MealType.dinner,"Pakistani",GoalType.Maintain,490,"🥘",
            listOf(i("Chicken",200.0,"g",M),i("Bell peppers",100.0,"g",V),i("Green chilies",2.0,"pcs",V),i("Tomato paste",2.0,"tbsp",P)),
            listOf("Stir-fry chicken with peppers","Add chilies and tomato sauce","Simmer until thick")),
        Meal(97,"Red Curry with Bamboo Shoots",MealType.dinner,"Thai",GoalType.Maintain,460,"🍲",
            listOf(i("Chicken",150.0,"g",M),i("Coconut milk",200.0,"ml",P),i("Bamboo shoots",100.0,"g",V),i("Red curry paste",2.0,"tbsp",P)),
            listOf("Simmer curry paste in coconut milk","Add chicken and bamboo shoots","Cook until done")),
        Meal(98,"Beef Bulgogi Bowl",MealType.lunch,"Korean",GoalType.Gain,640,"🍚",
            listOf(i("Marinated beef",200.0,"g",M),i("Rice",200.0,"g",P),i("Fried egg",1.0,"pc",D),i("Kimchi",50.0,"g",V)),
            listOf("Stir-fry bulgogi","Assemble bowl with rice and egg","Serve with kimchi")),
        Meal(99,"Baba Ganoush with Veggies",MealType.snack,"Lebanese",GoalType.Lose,180,"🍆",
            listOf(i("Roasted eggplant",200.0,"g",V),i("Tahini",2.0,"tbsp",P),i("Garlic",1.0,"clove",V),i("Carrot sticks",100.0,"g",V)),
            listOf("Blend eggplant with tahini and garlic","Serve with fresh carrot sticks")),
        Meal(100,"Adana Kebab",MealType.dinner,"Turkish",GoalType.Gain,680,"🍢",
            listOf(i("Ground lamb",250.0,"g",M),i("Onion",0.5,"pc",V),i("Paprika",1.0,"tsp",P),i("Bulgur pilaf",100.0,"g",P)),
            listOf("Mix lamb with spices","Grill on skewers","Serve over bulgur pilaf")),

        // ═══════════════════ NEWLY ADDED MEALS (101-120) ═══════════════════
        Meal(101,"Cottage Cheese & Peaches",MealType.breakfast,"American",GoalType.Lose,250,"🍑",
            listOf(i("Cottage cheese",200.0,"g",D),i("Fresh peaches",1.0,"pc",F),i("Almonds",15.0,"g",P)),
            listOf("Spoon cottage cheese into bowl","Top with sliced peaches and almonds")),
        Meal(102,"Almond Butter & Banana Toast",MealType.snack,"Mediterranean",GoalType.Gain,320,"🍌",
            listOf(i("Sourdough bread",2.0,"slices",P),i("Almond butter",2.0,"tbsp",P),i("Banana",1.0,"pc",F),i("Honey",1.0,"tsp",P)),
            listOf("Toast bread","Spread almond butter","Top with banana slices and honey")),
        Meal(103,"Zucchini Noodles with Pesto",MealType.lunch,"Italian",GoalType.Lose,220,"🥒",
            listOf(i("Zucchini noodles",300.0,"g",V),i("Basil pesto",2.0,"tbsp",P),i("Pine nuts",10.0,"g",P),i("Cherry tomatoes",5.0,"pcs",V)),
            listOf("Sauté zucchini noodles briefly","Toss with pesto and tomatoes","Garnish with pine nuts")),
        Meal(104,"Stir-Fried Tofu with Mixed Veg",MealType.dinner,"Chinese",GoalType.Maintain,350,"🍱",
            listOf(i("Firm tofu",200.0,"g",D),i("Bell peppers",100.0,"g",V),i("Snap peas",50.0,"g",V),i("Soy sauce",2.0,"tbsp",P)),
            listOf("Press and cube tofu","Stir-fry with vegetables and soy sauce")),
        Meal(105,"Natto with Rice & Egg",MealType.breakfast,"Japanese",GoalType.Gain,480,"🍚",
            listOf(i("Natto",1.0,"pack",P),i("Steamed rice",200.0,"g",P),i("Raw egg",1.0,"pc",D),i("Green onion",10.0,"g",V)),
            listOf("Mix natto with its sauce","Stir into hot rice with egg and onions")),
        Meal(106,"Cucumber Salsa with Baked Chips",MealType.snack,"Mexican",GoalType.Lose,140,"🥒",
            listOf(i("Cucumber",100.0,"g",V),i("Tomato",1.0,"pc",V),i("Lime juice",1.0,"tbsp",F),i("Baked tortilla chips",20.0,"g",P)),
            listOf("Dice cucumber and tomato","Mix with lime and salt","Serve with chips")),
        Meal(107,"Egg Curry with Paratha",MealType.lunch,"Indian",GoalType.Gain,580,"🍛",
            listOf(i("Boiled eggs",2.0,"pcs",D),i("Onion-tomato gravy",200.0,"ml",P),i("Whole wheat paratha",2.0,"pcs",P)),
            listOf("Simmer eggs in gravy","Serve hot with paratha")),
        Meal(108,"Vegetable Pulao",MealType.dinner,"Pakistani",GoalType.Lose,320,"🍚",
            listOf(i("Basmati rice",80.0,"g",P),i("Mixed vegetables",150.0,"g",V),i("Whole spices",5.0,"g",P)),
            listOf("Sauté spices and vegetables","Add rice and water","Cook until rice is fluffy")),
        Meal(109,"Thai Basil Tofu (Pad Krapow)",MealType.breakfast,"Thai",GoalType.Maintain,310,"🌿",
            listOf(i("Firm tofu",200.0,"g",D),i("Thai basil",20.0,"g",V),i("Chilies",2.0,"pcs",V),i("Soy sauce",2.0,"tbsp",P)),
            listOf("Crumble tofu and stir-fry with chilies","Add basil at the end","Serve with a fried egg if desired")),
        Meal(110,"Sweet Potato Rice Cakes",MealType.snack,"Korean",GoalType.Gain,290,"🍠",
            listOf(i("Rice cakes",100.0,"g",P),i("Sweet potato",100.0,"g",V),i("Honey",1.0,"tbsp",P)),
            listOf("Boil rice cakes and sweet potato","Sauté together with honey")),
        Meal(111,"Mujadara (Lentils & Rice)",MealType.lunch,"Lebanese",GoalType.Maintain,420,"🍚",
            listOf(i("Green lentils",100.0,"g",P),i("Basmati rice",100.0,"g",P),i("Caramelized onions",50.0,"g",V)),
            listOf("Cook lentils and rice together","Top with plenty of caramelized onions")),
        Meal(112,"Turkish Lentil Salad",MealType.dinner,"Turkish",GoalType.Maintain,340,"🥗",
            listOf(i("Red lentils",100.0,"g",P),i("Parsley",20.0,"g",V),i("Scallions",20.0,"g",V),i("Pomegranate molasses",1.0,"tbsp",P)),
            listOf("Boil lentils until tender but firm","Toss with herbs and molasses")),
        Meal(113,"Peanut Butter & Celery Sticks",MealType.snack,"American",GoalType.Gain,210,"🥜",
            listOf(i("Celery stalks",3.0,"pcs",V),i("Peanut butter",2.0,"tbsp",P),i("Raisins",10.0,"g",F)),
            listOf("Fill celery with peanut butter","Top with raisins (Ants on a log)")),
        Meal(114,"Greek Salad with Pita",MealType.breakfast,"Mediterranean",GoalType.Maintain,360,"🥗",
            listOf(i("Cucumber",100.0,"g",V),i("Tomato",100.0,"g",V),i("Feta",50.0,"g",D),i("Whole wheat pita",1.0,"pc",P)),
            listOf("Mix vegetables and feta","Serve with toasted pita")),
        Meal(115,"Baked White Fish with Lemon",MealType.dinner,"Italian",GoalType.Lose,280,"🐟",
            listOf(i("Cod fillet",200.0,"g",S),i("Lemon",1.0,"pc",F),i("Capers",1.0,"tbsp",P),i("Spinach",100.0,"g",V)),
            listOf("Bake fish with lemon and capers","Serve over wilted spinach")),
        Meal(116,"General Tso's Cauliflower",MealType.lunch,"Chinese",GoalType.Gain,450,"🥦",
            listOf(i("Cauliflower florets",300.0,"g",V),i("Cornstarch",20.0,"g",P),i("Spicy hoisin sauce",3.0,"tbsp",P),i("Rice",150.0,"g",P)),
            listOf("Coat and bake cauliflower","Toss in sauce","Serve over rice")),
        Meal(117,"Vegetable Tempura Bowl",MealType.dinner,"Japanese",GoalType.Maintain,420,"🍱",
            listOf(i("Assorted veg (yam, beans)",200.0,"g",V),i("Tempura batter",50.0,"g",P),i("Dashi dip",50.0,"ml",P),i("Rice",150.0,"g",P)),
            listOf("Batter and fry vegetables","Serve over rice with dip")),
        Meal(118,"Papaya with Lime",MealType.breakfast,"Mexican",GoalType.Lose,120,"🥭",
            listOf(i("Fresh papaya",200.0,"g",F),i("Lime juice",1.0,"tbsp",F),i("Tajin seasoning",1.0,"tsp",P)),
            listOf("Slice papaya","Drizzle with lime and Tajin")),
        Meal(119,"Mixed Vegetable Korma",MealType.lunch,"Indian",GoalType.Maintain,390,"🍛",
            listOf(i("Mixed veg",200.0,"g",V),i("Cashew paste",2.0,"tbsp",P),i("Coconut milk",50.0,"ml",P),i("Rice",100.0,"g",P)),
            listOf("Cook veg in creamy korma sauce","Serve with rice")),
        Meal(120,"Thai Green Papaya Salad (Som Tum)",MealType.snack,"Thai",GoalType.Lose,150,"🥗",
            listOf(i("Green papaya",150.0,"g",V),i("Peanuts",10.0,"g",P),i("Green beans",30.0,"g",V),i("Chili lime dressing",2.0,"tbsp",P)),
            listOf("Shred papaya","Pound with beans and peanuts","Toss with dressing")),

        // ═══════════════════ NEWLY ADDED MEALS (121-150) ═══════════════════
        Meal(121,"Bagel with Cream Cheese",MealType.breakfast,"American",GoalType.Gain,420,"🥯",
            listOf(i("Plain bagel",1.0,"pc",P),i("Cream cheese",50.0,"g",D),i("Smoked salmon",50.0,"g",S)),
            listOf("Toast bagel","Spread cream cheese","Top with smoked salmon")),
        Meal(122,"Lentil Stew with Kale",MealType.dinner,"Mediterranean",GoalType.Lose,290,"🍲",
            listOf(i("Green lentils",100.0,"g",P),i("Kale",100.0,"g",V),i("Carrots",50.0,"g",V),i("Vegetable broth",400.0,"ml",P)),
            listOf("Sauté carrots","Add lentils and broth","Simmer until tender","Add kale at the end")),
        Meal(123,"Pasta Primavera",MealType.lunch,"Italian",GoalType.Maintain,460,"🥦",
            listOf(i("Fusilli pasta",100.0,"g",P),i("Bell peppers",50.0,"g",V),i("Zucchini",50.0,"g",V),i("Parmesan",20.0,"g",D)),
            listOf("Cook pasta","Sauté vegetables","Toss together with cheese")),
        Meal(124,"Chicken & Corn Soup",MealType.dinner,"Chinese",GoalType.Lose,240,"🌽",
            listOf(i("Shredded chicken",100.0,"g",M),i("Creamed corn",200.0,"g",P),i("Egg",1.0,"pc",D),i("Ginger",5.0,"g",V)),
            listOf("Boil corn and ginger","Add chicken","Whisk in egg slowly")),
        Meal(125,"Onigiri Rice Balls",MealType.snack,"Japanese",GoalType.Maintain,180,"🍙",
            listOf(i("Sushi rice",100.0,"g",P),i("Nori seaweed",1.0,"sheet",P),i("Tuna mayo",30.0,"g",S)),
            listOf("Shape rice around filling","Wrap with seaweed")),
        Meal(126,"Beef Fajitas",MealType.dinner,"Mexican",GoalType.Maintain,520,"🥘",
            listOf(i("Steak strips",150.0,"g",M),i("Bell peppers",100.0,"g",V),i("Onion",50.0,"g",V),i("Tortillas",2.0,"pcs",P)),
            listOf("Sauté beef and veggies with fajita spices","Serve with warm tortillas")),
        Meal(127,"Baingan Bharta (Roasted Eggplant)",MealType.dinner,"Indian",GoalType.Lose,280,"🍆",
            listOf(i("Roasted eggplant",300.0,"g",V),i("Onion",50.0,"g",V),i("Tomato",50.0,"g",V),i("Green chilies",2.0,"pcs",V)),
            listOf("Mash roasted eggplant","Sauté with onion, tomato, and spices")),
        Meal(128,"Chicken Tikka Salad",MealType.lunch,"Pakistani",GoalType.Lose,340,"🥗",
            listOf(i("Chicken tikka",150.0,"g",M),i("Mixed greens",150.0,"g",V),i("Cucumber",50.0,"g",V),i("Lemon dressing",2.0,"tbsp",P)),
            listOf("Toss grilled chicken with greens and dressing")),
        Meal(129,"Thai Pineapple Fried Rice",MealType.lunch,"Thai",GoalType.Gain,560,"🍍",
            listOf(i("Rice",200.0,"g",P),i("Pineapple",100.0,"g",F),i("Cashews",30.0,"g",P),i("Shrimp",100.0,"g",S)),
            listOf("Stir-fry rice with shrimp, pineapple, and cashews")),
        Meal(130,"Japchae (Glass Noodles)",MealType.dinner,"Korean",GoalType.Maintain,480,"🍜",
            listOf(i("Sweet potato noodles",150.0,"g",P),i("Spinach",50.0,"g",V),i("Carrots",50.0,"g",V),i("Beef strips",100.0,"g",M)),
            listOf("Boil noodles","Sauté with veggies and beef in sesame-soy sauce")),
        Meal(131,"Kafta Bil Sanieh (Meatloaf)",MealType.dinner,"Lebanese",GoalType.Gain,640,"🥘",
            listOf(i("Ground beef",200.0,"g",M),i("Potatoes",150.0,"g",V),i("Tomato sauce",100.0,"ml",P),i("Parsley",20.0,"g",V)),
            listOf("Layer meat and potatoes in pan","Cover with sauce and bake")),
        Meal(132,"Simit (Turkish Bagel)",MealType.breakfast,"Turkish",GoalType.Maintain,320,"🥨",
            listOf(i("Simit bread",1.0,"pc",P),i("Feta cheese",30.0,"g",D),i("Olives",20.0,"g",P),i("Turkish tea",200.0,"ml",P)),
            listOf("Serve fresh simit with cheese and olives")),
        Meal(133,"Trail Mix",MealType.snack,"American",GoalType.Gain,280,"🥜",
            listOf(i("Almonds",20.0,"g",P),i("Walnuts",20.0,"g",P),i("Dried cranberries",20.0,"g",F),i("Dark chocolate",10.0,"g",P)),
            listOf("Mix all in a small bag")),
        Meal(134,"Tzatziki with Pita Bread",MealType.snack,"Mediterranean",GoalType.Lose,210,"🥙",
            listOf(i("Greek yogurt",100.0,"g",D),i("Cucumber",50.0,"g",V),i("Garlic",1.0,"clove",V),i("Pita bread",1.0,"pc",P)),
            listOf("Mix yogurt, grated cucumber, and garlic","Serve with toasted pita")),
        Meal(135,"Minestrone Soup",MealType.dinner,"Italian",GoalType.Lose,320,"🥣",
            listOf(i("Mixed vegetables",200.0,"g",V),i("Kidney beans",50.0,"g",P),i("Small pasta",30.0,"g",P),i("Tomato broth",300.0,"ml",P)),
            listOf("Simmer veggies and beans in broth","Add pasta and cook until tender")),
        Meal(136,"Kung Pao Shrimp",MealType.lunch,"Chinese",GoalType.Maintain,420,"🍤",
            listOf(i("Shrimp",200.0,"g",S),i("Peanuts",30.0,"g",P),i("Dried chilies",5.0,"pcs",P),i("Zucchini",100.0,"g",V)),
            listOf("Stir-fry shrimp with chilies, peanuts, and zucchini")),
        Meal(137,"Chicken Katsu",MealType.dinner,"Japanese",GoalType.Gain,680,"🍗",
            listOf(i("Chicken breast",180.0,"g",M),i("Panko breadcrumbs",50.0,"g",P),i("Egg",1.0,"pc",D),i("Rice",150.0,"g",P)),
            listOf("Bread and fry chicken","Serve with rice and tonkatsu sauce")),
        Meal(138,"Mexican Street Corn (Elote)",MealType.snack,"Mexican",GoalType.Maintain,250,"🌽",
            listOf(i("Corn on the cob",1.0,"pc",V),i("Mayonnaise",1.0,"tbsp",D),i("Cotija cheese",20.0,"g",D),i("Chili powder",1.0,"tsp",P)),
            listOf("Grill corn","Slather with mayo, cheese, and chili")),
        Meal(139,"Saag Paneer",MealType.dinner,"Indian",GoalType.Maintain,460,"🌿",
            listOf(i("Spinach",300.0,"g",V),i("Paneer",150.0,"g",D),i("Ginger",5.0,"g",V),i("Garlic",2.0,"cloves",V)),
            listOf("Cook spinach until wilted and blend","Sauté paneer and mix into spinach")),
        Meal(140,"Lamb Tikka",MealType.dinner,"Pakistani",GoalType.Gain,580,"🍢",
            listOf(i("Lamb chunks",200.0,"g",M),i("Yogurt",50.0,"g",D),i("Tikka spices",2.0,"tbsp",P),i("Naan",1.0,"pc",P)),
            listOf("Marinate and grill lamb","Serve with warm naan")),
        Meal(141,"Tom Kha Gai (Coconut Soup)",MealType.dinner,"Thai",GoalType.Maintain,380,"🍲",
            listOf(i("Chicken",150.0,"g",M),i("Coconut milk",200.0,"ml",P),i("Mushrooms",100.0,"g",V),i("Lemongrass",2.0,"stalks",V)),
            listOf("Simmer chicken and mushrooms in coconut broth with aromatics")),
        Meal(142,"Kimchi Jjigae (Stew)",MealType.dinner,"Korean",GoalType.Lose,340,"🥘",
            listOf(i("Kimchi",200.0,"g",V),i("Pork belly",50.0,"g",M),i("Tofu",100.0,"g",D),i("Green onions",20.0,"g",V)),
            listOf("Boil kimchi and pork","Add tofu and onions")),
        Meal(143,"Labneh with Olives & Zaatar",MealType.breakfast,"Lebanese",GoalType.Maintain,290,"🥛",
            listOf(i("Labneh",100.0,"g",D),i("Olives",30.0,"g",P),i("Zaatar",1.0,"tbsp",P),i("Pita bread",1.0,"pc",P)),
            listOf("Spread labneh on plate","Top with olives and zaatar","Serve with pita")),
        Meal(144,"Pide (Turkish Pizza)",MealType.lunch,"Turkish",GoalType.Gain,560,"🍕",
            listOf(i("Dough",150.0,"g",P),i("Ground beef",100.0,"g",M),i("Cheese",50.0,"g",D),i("Spinach",30.0,"g",V)),
            listOf("Shape dough into boat","Fill with meat and cheese","Bake until golden")),
        Meal(145,"Cottage Cheese with Berries",MealType.snack,"American",GoalType.Lose,160,"🍓",
            listOf(i("Cottage cheese",150.0,"g",D),i("Strawberries",50.0,"g",F),i("Blueberries",50.0,"g",F)),
            listOf("Mix berries into cottage cheese")),
        Meal(146,"Mediterranean Wrap",MealType.lunch,"Mediterranean",GoalType.Maintain,420,"🌯",
            listOf(i("Whole wheat wrap",1.0,"pc",P),i("Hummus",2.0,"tbsp",P),i("Grilled veggies",100.0,"g",V),i("Feta",20.0,"g",D)),
            listOf("Spread hummus on wrap","Fill with veggies and feta","Roll and serve")),
        Meal(147,"Spaghetti Aglio e Olio",MealType.dinner,"Italian",GoalType.Lose,380,"🍝",
            listOf(i("Spaghetti",100.0,"g",P),i("Garlic",3.0,"cloves",V),i("Olive oil",3.0,"tbsp",P),i("Red pepper flakes",1.0,"tsp",P)),
            listOf("Sauté garlic in oil","Toss with cooked spaghetti and flakes")),
        Meal(148,"Egg Drop Soup",MealType.snack,"Chinese",GoalType.Lose,120,"🥣",
            listOf(i("Chicken broth",400.0,"ml",P),i("Egg",1.0,"pc",D),i("Cornstarch",1.0,"tsp",P),i("Green onion",10.0,"g",V)),
            listOf("Boil broth","Whisk in egg slowly","Thicken slightly with cornstarch")),
        Meal(149,"Grilled Mackerel",MealType.dinner,"Japanese",GoalType.Maintain,450,"🐟",
            listOf(i("Mackerel fillet",200.0,"g",S),i("Radish",50.0,"g",V),i("Lemon",1.0,"pc",F),i("Rice",150.0,"g",P)),
            listOf("Grill mackerel","Serve with grated radish, lemon, and rice")),
        Meal(150,"Tostadas with Beans & Cheese",MealType.snack,"Mexican",GoalType.Gain,310,"🌮",
            listOf(i("Crispy tostadas",2.0,"pcs",P),i("Refried beans",100.0,"g",P),i("Cheese",30.0,"g",D),i("Salsa",2.0,"tbsp",P)),
            listOf("Spread beans on tostadas","Top with cheese and salsa"))
    )

    fun availableCuisines(): List<String> = all.map { it.cuisine }.distinct().sorted()

    fun getFilteredMeals(
        type: MealType? = null,
        cuisine: String? = null,
        goalType: GoalType? = null
    ): List<Meal> = all.filter { meal ->
        (type == null || meal.type == type) &&
        (cuisine == null || cuisine == "All" || meal.cuisine.equals(cuisine, ignoreCase = true)) &&
        (goalType == null || meal.goalType == goalType)
    }
}
